Title = "Airkoala's Blog"
FaviconHref = "/assets/avatar_16.gif"
Hostname = "airkoala.lol"

[Author]
Name = "Airkoala"
AvatarHref = "/assets/avatar.gif"
Blurb = """
Deleniti voluptatibus sint aut. Possimus consectetur numquam et. Ut ut error dolor.<br>

Omnis occaecati sed ex quia nam eaque quam quidem. Reprehenderit assumenda <b>error</b> aut ducimus. Quisquam quas et corrupti veritatis sed ut quae sint. Tempore saepe consequatur dolorem consequatur. Architecto repudiandae dolor et vero doloribus maxime iste architecto.
"""

[[HeaderLinks]]
Name = "GitHub"
Href = "https://github.com/airkoala"

[[HeaderLinks]]
Name = "Twitter"
Href = "https://twitter.com/AirKoala_"

