Title = "Airkoala's Blog"
FaviconHref = "/assets/favicon.ico"
Hostname = "airkoala.lol"

[Author]
Name = "Airkoala"
AvatarHref = "/assets/avatar.gif"
Blurb = """
Hi !
<br>
I'm Airkoala and welcome to my mental asylum. This is where I will post my rants and shit I guess? I don't do social
media so consider this to be like my Xitter (formerly X) or something idk.
<br>
<i class="fa-brands fa-discord"></i> @airkoala
"""

[[HeaderLinks]]
Name = "GitHub"
Href = "https://github.com/airkoala"
