Title = "No, you don't need to dockerise your MERN app for the cloud — The File-Access Go Blog Stack"
ThumbnailHref = "/assets/1-fagblog-stack/hardware.jpg"
Timestamp = 2025-04-19T18:21:50+10:00
Summary = "In this post, I go over the decisions made in writing the engine for this blog, and details over how I chose to host the server."
